### PR TITLE
support sequence responses in JSON configuration

### PR DESCRIPTION
**Pull request by hkliya**

### CODE REVIEW

**Comment by tyx** [comment]
Hello,

Any plan to finish this feature ? Would be very helpful

**Comment by iambowen** [comment]
@tyx   https://github.com/dreamhead/moco/blob/master/moco-doc/global-settings.md  you should check this out, moco has already support multi configurations, and @dreamhead  I think you should close this issue.

**Comment by tyx** [comment]
I don't think it is the same we expect. We still need something to mock `/foo` several times. First call should answer 200, second call should answer 404 for example.

**Comment by dreamhead** [comment]
@tyx why don't you use Java API for `seq`?

**Comment by tyx** [comment]
Because we don't do Java ;) We use moco as an external tool through http. 

And it does a great job, this is really the only missing feature !

**Pull request closed without merging**
